[package]
name = "ray-tracing-rust"
version = "0.1.0"
authors = ["DjGorillaz <djg2008@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
